[package]
name = "fastbootd-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
libc = "0.2.142"
libusb1-sys = "0.6.4"
nix = "0.26.2"
once_cell = "1.17.1"
